#! /bin/bash

EXE="array_lock_variable_size"
OUT="measure_array_pad.log"
echo "Saving out to $OUT"
echo "-----------" > $OUT

make &> /dev/null


if [ -x /usr/bin/time ]
then 
	TIME='/usr/bin/time -f "  times: real %E, user %U, sys %S"'
else
	TIME=time
fi


for size in 1 2 4 8 16 32 128 256
do
	echo >> $OUT
	echo -- \[array_$size\] -- >> $OUT
	for i in `seq 4`
	do
		(eval $TIME ./$EXE $size) &>> $OUT
		echo -n " [$i]" 
		sleep 1
	done
	echo

	echo --- >> $OUT
done

 
